name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          IMAGE_TAG=$(git log -1 --pretty=format:"%h")
          docker build -t jibu07/jibinkoshy.world:$IMAGE_TAG .
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

      - name: Push Docker Image
        run: docker push jibu07/jibinkoshy.world:$IMAGE_TAG
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
