name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: . # The path to the directory containing the Dockerfile (current directory)
          push: true # Set to "true" if you want to push the image to a container registry

          # Replace "your-dockerhub-username" and "your-image-name" with appropriate values
          tags: jibu07/jibinkoshy.world:latest
