name: website deployment
on: [push]
jobs:  
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: deploy website to example.com
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
        with:
          source: "./*"
          target: "/home/xminds/github-action-test"
          strip_components: 1
